import html

from manhwateca.reporting.styles import COMMON_CSS, COMMON_JS


def build_html_page(
    title,
    subtitle,
    summary_cards_html,
    page_body_html,
    extra_css="",
    extra_js="",
):
    return "\n".join([
        "<!DOCTYPE html>",
        "<html lang='pt-BR'>",
        "<head>",
        "<meta charset='UTF-8'>",
        "<meta name='viewport' content='width=device-width, initial-scale=1.0'>",
        f"<title>{html.escape(str(title))}</title>",
        "<style>",
        COMMON_CSS,
        extra_css,
        "</style>",
        "</head>",
        "<body>",
        "<header class='topbar'>",
        "<div class='topbar-inner'>",
        "<div class='brand-row'>",
        "<div class='brand'>",
        f"<h1>{html.escape(str(title))}</h1>",
        f"<div class='subtitle'>{html.escape(str(subtitle))}</div>",
        "</div>",
        summary_cards_html,
        "</div>",
        "<div class='toolbar'>",
        "<input class='search' id='search' type='search' "
        "placeholder='Buscar obra...' autocomplete='off'>",
        "<div class='actions'>",
        "<button type='button' id='expandAll'>Expandir Tudo</button>",
        "<button type='button' id='collapseAll'>Recolher Tudo</button>",
        "</div>",
        "</div>",
        "</div>",
        "</header>",
        "<main class='page'>",
        page_body_html,
        "</main>",
        "<script>",
        COMMON_JS,
        extra_js,
        "</script>",
        "</body>",
        "</html>",
    ])
